# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: User

# Model Form Field configuration
form: $/frontend/user/models/user/fields.yaml

# Model Class name
modelClass: Frontend\User\Models\User

# Default redirect location
defaultRedirect: frontend/user/users

# Create page
create:
    redirect: frontend/user/users/preview/:id
    redirectClose: frontend/user/users

# Update page
update:
    redirect: frontend/user/users/update/:id
    redirectClose: frontend/user/users/preview/:id
