# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    groups:
        # Filter name
        label: Group
        # Model Class name
        modelClass: Frontend\User\Models\UserGroup
        # Model attribute to display for the name
        nameFrom: name
        # Filter scope
        scope: filterByGroup

    created_date:
        label: Registered
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    activated:
        # Filter name
        label: Activated
        # Filter type
        type: switch
        # SQL conditions
        conditions:
            - is_activated = '0'
            - is_activated = '1'
