# ===================================
#  List Behavior Config
# ===================================

# List Title
title: Manage Users

# Model List Column configuration
list: $/abhimanyu/user/models/user/columns.yaml

# Model Class name
modelClass: Abhimanyu\User\Models\User

# Link URL for each record
recordUrl: user/users/preview/:id

# Message to display if the list is empty
noRecordsMessage: There are no records in this view

# Records to display per page
recordsPerPage: 20

# Display checkboxes next to each record
showCheckboxes: true

# Displays the list column set up button
showSetup: true

# Filter widget configuration
filter: config_filter.yaml

# Toolbar widget configuration
toolbar:

    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: Search...
