# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Group

# Model Form Field configuration
form: $/frontend/user/models/usergroup/fields.yaml

# Model Class name
modelClass: Frontend\User\Models\UserGroup

# Default redirect location
defaultRedirect: frontend/user/usergroups

# Create page
create:
    title: Create User Group
    redirect: frontend/user/usergroups/update/:id
    redirectClose: frontend/user/usergroups

# Update page
update:
    title: Edit User Group
    redirect: frontend/user/usergroups
    redirectClose: frontend/user/usergroups

# Preview page
preview:
    title: Edit User Group
